# docker-compose.yml
services:
  seed:
    build: .
    command: ["serve", "--ip", "0.0.0.0", "--port", "4001"]
    # publish seed UDP to host for optional local debugging
    ports:
      - "4001:4001/udp"
    networks: [kadnet]
    restart: unless-stopped

  node:
    build: .
    # Every container has its own network namespace, so they can reuse port 4001
    command: ["serve", "--ip", "0.0.0.0", "--port", "4001", "--bootstrap", "seed:4001"]
    # no need to publish ports for the other nodes; they talk inside the kadnet bridge
    expose:
      - "4001/udp"
    networks: [kadnet]
    restart: unless-stopped

networks:
  kadnet:
    name: kadnet
    driver: bridge
