# docker-compose.yml
services:
  seed:
    build: .
    command: ["serve", "--ip", "0.0.0.0", "--port", "4001"]
    # publish seed UDP to host for optional local debugging
    ports:
      - "4001:4001/udp"
    networks: [kadnet]
    restart: unless-stopped

  node:
    build: .
    command: ["serve", "--ip", "0.0.0.0", "--port", "4001", "--bootstrap", "seed:4001"]
    expose:
      - "4001/udp"
    networks: [kadnet]
    restart: unless-stopped

networks:
  kadnet:
    name: kadnet
    driver: bridge
