version: "3.8"
services:
  kademliaNodes:
    image: kadlab:latest
    command: ["kadlab","node","--listen=:4000"]
    # Publish UDP only if you want to reach from the host; not needed for in-cluster tests:
    # ports:
    #   - "4000:4000/udp"
    deploy:
      mode: replicated
      replicas: 1   # ignored by docker compose (non-swarm); used by swarm
      restart_policy:
        condition: on-failure
    networks:
      - kademlia_network

networks:
  kademlia_network:
    driver: bridge
